---
- name: "Storage | Install LVM tools"
  tags: [storage, lvm]
  ansible.builtin.apt:
    name: lvm2
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Storage | Create a volume group for the storage"
- name: "Storage | Create a logical volume for the storage"
  when: not udev_rules
  tags: [storage, lvm]
  community.general.lvol:
    vg: "{{ virtual_group }}"
    lv: "{{ logical_volume }}"
    size: "{{ size }}"
    opts: "--config 'activation/udev_rules=0'"

- name: "Storage | Create a logical volume for the storage"
  when: udev_rules
  tags: [storage, lvm]
  community.general.lvol:
    vg: "{{ virtual_group }}"
    lv: "{{ logical_volume }}"
    size: "{{ size }}"
    opts: "--config 'activation/udev_rules=1'"

- name: "Storage | Create a filesystem for the storage"
  tags: storage
  community.general.filesystem:
    dev: "/dev/{{ virtual_group }}/{{ logical_volume }}"
    fstype: "{{ fs_type }}"

- name: "Storage | Create a mountpoint for the storage"
  tags: storage
  ansible.builtin.file:
    path: "{{ storage_mountpoint }}"
    state: directory
    owner: "{{ mountpoint_owner }}"
    group: "{{ mountpoint_group }}"
    mode: "{{ storage_mountpoint_mode }}"

- name: "Storage | Mount the main storage"
  tags: storage
  ansible.posix.mount:
    src: "/dev/{{ virtual_group }}/{{ logical_volume }}"
    path: "{{ storage_mountpoint }}"
    fstype: "{{ fs_type }}"
    state: mounted
