---
dependency:
  name: galaxy

driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: local
    host: 127.0.0.1
    user: $USER
    ansible_connection: local
    become: true
    become_method: sudo

provisioner:
  name: ansible

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
